Changed admins and updated mangainers. Also scrubbed teams
emporous/.github pull request #3
Opened 2022-08-08 17:54 UTC by christianh814

Fixes #2 

Signed-off-by: Christian Hernandez <christian@codefresh.io>

2022-08-10 04:41 UTC, sabre1041 requested changes
Thanks @christianh814 for kicking this off.

As noted in the specific in line comment, would you be able to also include the sub teams for maintainers? The permissions associated with the maintainers subteam will be different than the general team

2022-08-10 04:41 UTC, sabre1041 commented on peribolos.yaml
> +      ci:
Can the subteams for maintainers also be included?

2022-08-10 19:20 UTC, christianh814 commented on peribolos.yaml
> +      ci:
> Can the subteams for maintainers also be included?

Latest update should have fixed this. PTAL

https://github.com/uor-framework/.github/pull/3/commits/c409e6fb70ee72eb8d8b4762c3635432cbe23275

2022-08-11 23:12 UTC, sabre1041 approved these changes
LGTM

2022-08-11 23:12 UTC, merged